# Generated by Django 5.2.1 on 2025-05-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='', verbose_name='документ')),
                ('word_frequency', models.JSONField(blank=True, null=True, verbose_name='частоты слов')),
                ('time_processed', models.FloatField(blank=True, null=True, verbose_name='время обработки, c')),
            ],
        ),
    ]
