# Generated by Django 5.2 on 2025-04-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='word_frequency',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
